### ISSUE TITLE
Releaseing 2.8 and 3.0 of network-bsd

### ISSUE THREAD

**Issue by kazu-yamamoto** [haskell/network-bsd#1]
@phadej @hvr @eborden @vshabanov @Mistuke @hasufell @fumieval I please invite necesary people.

I have created `network-bsd` to provide `Network.BSD`. I'm going release two versions:

- 2.8.0.0: this version is a dummy package. No module is exported. (`2.8` branch)
- 3.0.0.0: `Netwrok.BSD` is exported (`master`)

Since `network-bsd` depends on `network`, `network-bsd-flag` is not necessary. Please check them and give me comments.

**Comment by Mistuke** [comment]
Why not just start the package version at 1.0? especially if the point is for it to live independently of network that makes a bit more sense to me.

**Comment by hvr** [comment]
You write

> Version 2.8 (unlike the following versions) is a dummy package that prevents module name clashes between network-bsd and network.

Why would there even be a name-clash? `network-bsd` depends on `network >= 3`, so it can never clash with `network < 2.9`.

Moreover, if there is a range of versions of the `network` package extending up to including 2.8.0.0 which had their observable `Network.BSD` API unchanged, you can actually make use of `reexported-modules` to provide a single not-so-dummy `network-bsd-2.8.0.0` which exports a well-defined API of `network`'s legacy Network.BSD either as reexported-module or as exposed-module (i.e. no need for a distinct `network-bsd-3.0.0.0` version!), depending on the version of `network`. If it's unclear what I mean, I can elaborate this a bit more, but I feel like this would be the most optimal and elegant solution.


Btw, the instructions for specifying version bounds in

```
 You can control the version of the network package.
  .
  Example 1:
  .
  > library
  >     build-depends: network >= 3
  >                  , network-bsd
  .
  Example 2:
  .
  > library
  >     build-depends: network >= 2.7 && < 3
  > ,   network-bsd
```

are not a good recommendation in the context of the PVP and/or Hackage guidelines which require to accurately specify which version of an API your code requires.

**Comment by kazu-yamamoto** [comment]
@hvr I think your solution is excellent. Could you send a PR?

**Comment by kazu-yamamoto** [comment]
@Mistuke If hvr's solution works as we expect, I don't mind the version number. :-)

**Comment by hvr** [comment]
@kazu-yamamoto sure! I'm a bit busy though; it may take a couple days till I get  to this, if you can wait.

**Comment by kazu-yamamoto** [comment]
@hvr No rush!

**Comment by hvr** [comment]
@kazu-yamamoto I've found a bit of time and drafted the scheme I consider best in the 3 Git branches `wip/network-2.7.0.0` `wip/network-2.8.0.0` `wip/network-2.8.0.1` in this repo respectively; it turns out that there were observable API changes from network-2.7 to network-2.8 in the `Network.BSD` and the only way I can think of to do this correctly is to have a correlated series of thin shim `reexported-modules` packages acting as a kind of "API version homomorphism" for the past versions of `network` we want to provide shims for. Please take a look and let me know if you have any questions.

PS: I've also uploaded a preview candidate at http://hackage.haskell.org/package/network-bsd-2.8.0.1/candidate

**Comment by kazu-yamamoto** [comment]
> it turns out that there were observable API changes from network-2.7 to network-2.8 in the `Network.BSD` 

I don't understand this. The APIs of `Network.BSD` are the same in 2.7.0.0, 2.7.0.1, 2.7.0.2 and 2.8.0.0.

Q1) Why do you use 2.8.0.1 instead of 2.8.0.0?

Q2) Are you planning to release 2.7.0.0 and 2.8.0.0, too?

**Comment by kazu-yamamoto** [comment]
Ping @hvr

**Comment by kazu-yamamoto** [comment]
Ping @hvr

**Comment by kazu-yamamoto** [comment]
Ping @hvr

**Comment by hvr** [comment]
@kazu-yamamoto sorry; next time, please email me or ping me on IRC (or even Twitter) -- I get so many GitHub notifications it's easy to miss one :-/

> > it turns out that there were observable API changes from network-2.7 to network-2.8 in the `Network.BSD`
> 
> I don't understand this. The APIs of `Network.BSD` are the same in 2.7.0.0, 2.7.0.1, 2.7.0.2 and 2.8.0.0.

They *are* subtly different! :-)

It's easily possible to write a program that uses `network >= 2.7 && < 2.9` and only makes use of `Network.BSD`, specifically


```hs
import Network.BSD

main :: IO ()
main = print $ compare (0x1234 :: PortNumber) (0x3412 :: PortNumber)
```

would return differnent results depending on whether `network-bsd` reexports `PortNumber` from `network-2.7` or `network-2.8` -- and that would violate the PVP which requires that the package version of `network-bsd` alone (which is the one you declare in your `.cabal` file) sufficiently determines your API contract. Otherwise you'd have to always declare a dependency on  `network-bsd` and `network` to determine the API of `network-bsd` which breaks the PVP formalism.

> Q1) Why do you use 2.8.0.1 instead of 2.8.0.0?

Because contrary to what I thought originally, you need both 2.8.0.0

- http://hackage.haskell.org/package/network-bsd-2.8.0.0/candidate

which is a `build-type: Simple` and reexports the modules from `network` and

- http://hackage.haskell.org/package/network-bsd-2.8.0.1/candidate

which uses `build-type: Configure` and has the actual impl; i.e. you have two different `build-types` and a significantly different package description that it's cleaner to separate it out like this and the solver pick the right one (depending on which version of `network` you have in your build-plan)
 
> Q2) Are you planning to release 2.7.0.0 and 2.8.0.0, too?

yeah, 2.8.0.0 must be released for this scheme to make sense

I'd also release network-bsd-2.7.0.0 as it's easy to do and validates the approach.

**Comment by kazu-yamamoto** [comment]
OK. Please go ahead.

**Comment by hvr** [comment]
@kazu-yamamoto while reviewing the release I noticed something that might cause problems: both `network` and `network-bsd` have 

    install-includes: HsNet.h HsNetDef.h

Why are those exposed in the first place? Is there reasonable need for packages depending on `network` or `network-bsd` to be able to include those?

At the very least,  they should be named differently in `network-bsd` so that they don't clobber each other; even better yet if we don't need them to be exposed at all.

PS: I've published the two shim package releases https://hackage.haskell.org/package/network-bsd-2.7.0.0 and https://hackage.haskell.org/package/network-bsd-2.8.0.0 to Hackage as those aren't affected by the `install-includes` issue; I'm holding off with the `network-bsd-2.8.0.1` release until we can resolve the`install-includes` issue.

**Comment by kazu-yamamoto** [comment]
> Why are those exposed in the first place? Is there reasonable need for packages depending on `network` or `network-bsd` to be able to include those?

I don't know. SInce I inherited the maintenance, I think I have not changed it.

I'm not sure but `doctest` in the test suite might use it.

**Comment by hvr** [comment]
@kazu-yamamoto Ok, I'm looking into whether `network-bsd` can get rid of those somewhat duplciated header files, and instead reuse the ones traditionally provided by `network` rather than creating its own ones.

PS: I also just noticed that I should try to forward port @Mistuke's windows header related cleanups to `Network.BSD` and test this on a Win32 environment

**Comment by kazu-yamamoto** [comment]
I found that network-bsd was released. Let's close this.
