### ISSUE TITLE
Upper bound for network seems to be too tight

### ISSUE THREAD

**Issue by maoe** [haskell/network-bsd#2]
Is there any reason that `network-bsd` has to specify `network < 3.0.1` rather than `network < 3.1`? If network complies with PVP, shouldn't this package use `< 3.1`?

EDIT: This bound doesn't allow the latest network package.

**Comment by hvr** [comment]
Sorry for responding so late; for some reason I missed the GitHub notification.

As to your question, yes there is! It's effectively required to properly uphold the PVP contract. It's also explained at https://github.com/haskell/network-bsd/blob/master/network-bsd.cabal#L73-L78

So while `network < 3.1` might be more convenient it would risk having to retroactively outlaw already established build-plans. It's more preferable to err on the side of correctness, so we operate instead in a more principled opt-in scheme rather than a fast-and-loose opt-out scheme :-)

That being said, I reviewed the changes in `network-3.0.1.0` to see if I can safely relax the upper bound, and performed a respective [metadata revision](http://hackage.haskell.org/package/network-bsd-2.8.1.0/revisions/)

**Comment by maoe** [comment]
Thanks!
